# Generated by Django 5.0.2 on 2024-02-14 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='description',
            new_name='critical_description',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='title',
        ),
        migrations.AddField(
            model_name='snack',
            name='name',
            field=models.CharField(blank=True, default='Goodies', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
